### ISSUE TITLE
Blog guidelines

### ISSUE THREAD

**Issue by phynxinferno** [CBStudentCommunity/Homepage#7]

**Comment by gecotron** [comment]
its coming along :)

**Comment by gecotron** [comment]
# Blog Guidelines (In progress, subject to change)
The following are rules you are required to follow in order to make a blog post on website, if you are ever unsure about whether your post falls within the rules, please consult an admin or similarly high level contributor to confirm.

## Topic
The topic must be civil and relate in some way to Colonel By or the Colonel By Student Community.  
**We will not accept or tolerate any post with topics of hate, misinformation, bigotry or segregation.**
## Language
Language must be relatively formal and civil. No slurs, swear words, etc...
## Reviewing
No blog post can simply be added, it must be submitted as a pull request so that the post can be reviewed, in order to confirm that it follows the guidelines.

Please give any commentary and additions you feel are important

**Comment by gecotron** [comment]
Blog Guidelines added. If anyone thinks there should be some changes, reopen this issue or create a new one
